### ISSUE TITLE
В массиве не обьекты блюд, а строки

### ISSUE THREAD

**Issue by uzarsalan** [SanzhiGilb/home_workSAnzhi#3]
Обрати внимание, ты помещаешь в массив не обьекты блюд, а просто строки с их названиями. Строки выделяются кавычками

https://github.com/SanzhiGilb/home_workSAnzhi/blob/5bcd052b70e7239734e3f6f83d6034bb98763305/%D1%83%D1%80%D0%BE%D0%BA9/script.js#L24

**Comment by SanzhiGilb** [comment]
Привет! Изменил код, пушем добавил в него
